import {LayoutProps} from "@utils/commonProps"
import Head from 'next/head'
import dynamic from "next/dynamic"

const Layout = ({currentPage, children}: LayoutProps) => {
  const Navbar = dynamic(() => import("@components/Navbar"), {ssr: false})
  return (
    <div>
      <Head>
        <title>{currentPage} - Dimitrios Valodimos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="w-4/5 mx-auto">
        {children}
      </main>
    </div>
  )
}

export default Layout;
