import {LayoutProps} from "@utils/commonProps"
import Head from 'next/head'
import Navbar from "@components/Navbar"

const Layout = ({currentPage, children}: LayoutProps) => {
  return (
    <div>
      <Head>
        <title>{currentPage} - Dimitrios Valodimos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      {children}
    </div>
  )
}

export default Layout;
